### ISSUE TITLE
Assets do not work correctly

### ISSUE THREAD

**Issue by bhairava3** [mvanvu/hummingbird-cms#1]
Hello. 
Installed Hummingbird CMS, everything is fine, the admin panel and site are displayed, but the path to css and js is wrong.

css: `<link rel="stylesheet" type="text/css" href="//home/cms/web/mysite.com/public_html/public/assets/compressed/20a83aff8e870126e8f612b2aedb63d4.css?1585233436" />`

js:
`<script src="//home/cms/web/mysite.com/public_html/public/assets/compressed/f65624cd41de4b2cb0d8121c0be0d995.js?1585233436"></script>`

installed software on the server:
Debian 9
PHP 7.4.4 (extensions: Curl  GetText  Gd  Json  Mbstring  FileInfo  OpenSSL  PDO Mysql)
Phalcon 4.0.5
Database version: 5.5.5-10.1.44-MariaDB-0+deb9u1

**Comment by mvanvu** [comment]
@bhairava3 I don't use Debian and don't check on it yet. The issue came from the ROOT_URI you can check it at /src/app/Config/Define.php. In your case the ROOT_URI should be empty. 

When you resolve this please tell me what you do, I will consider to update the Cms core.

Thank you.

**Comment by bhairava3** [comment]
@mvanvu I figured it out yesterday, it really was this constant, I had to make it an empty line. :)
A good implementation, but the only thing I do not like is third-party libraries, there are a lot of them due to which it seems to me that performance is lost.
But in general, everything is fine! Excuse me, please, google translator. :)
