### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sinabio** [mvanvu/hummingbird-cms#3]
This is great project,
if it's possible add documentation/wiki (in any language which is easy for you).
so it's easier to develop plugins and...

Thanks

**Comment by mvanvu** [comment]
Hi there,
Thanks, but I'm developing the new version for Nginx and fix any existing issues. The time for the document will be a delay.

To develop plugin you can follow: 
* Social login: https://github.com/mvanvu/hummingbird-sociallogin 
* Backup system: https://github.com/mvanvu/hummingbird-backup
